### PR TITLE
added SonarQube

### PR DESCRIPTION
**Pull request by martino-vic**
just learned about them in this [reddit comment](https://www.reddit.com/r/perl/comments/n7ns85/comment/gxf2y4s/?utm_source=share&utm_medium=web2x&context=3) while I was trying to find out what ever happened to kritika.io

### CODE REVIEW

**Comment by ligurio** [comment]
@martino-vic Could you rebase on master? (GH shows a message "This branch cannot be rebased due to conflicts").

**Comment by martino-vic** [comment]
I'm a bit new to github and I tried to look for tutorials how to rebase for almost an hour now, but I can't figure it out because I have made the changes in my browser without cloning the repo. What do you recommend me to do

**Comment by martino-vic** [comment]
didn't manage to rebase so I closed it, deleted the fork, made a new one copy-pasted the same changes and created a new pull request

**Comment by martino-vic** [comment]
modern problems require modern solutions

**Pull request closed without merging**
