### PR TITLE
Added Jenkins CI/CD

### PR DESCRIPTION
**Pull request by baymac**
Jenkins is an open-source project for automating your projects. Jenkins works as a standalone CI server, or you can turn it into a continuous delivery platform for virtually any of your projects. Large community with leading software brands involved in development

### CODE REVIEW

**Comment by baymac** [comment]
@ligurio Can you comment on this?

**Comment by ligurio** [comment]
Hi! Why do you insert a link to Gitlab CI in a row about Jenkins?

**Comment by baymac** [comment]
Oops! I referenced this row from that of gitlab, in the end I forgot to edit the link. I have added the correct link in my last commit.

**Comment by baymac** [comment]
I don't know why the build fails now. Btw since I made this PR, the upstream repo has changed. Should I make a new PR?

**Comment by ligurio** [comment]
Merged, thanks!

**Comment by baymac** [comment]
yw. :)

**Pull request merged**
